<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="5" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="180" started-at="2018-10-13T16:09:13Z" finished-at="2018-10-13T16:09:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="180" started-at="2018-10-13T16:09:13Z" finished-at="2018-10-13T16:09:13Z">
      <class name="jp.imanaga.marklogic_util.QueryRunnerTest">
        <test-method status="PASS" signature="normal(java.lang.String, [Ljava.lang.String;)[pri:0, instance:jp.imanaga.marklogic_util.QueryRunnerTest@c038203]" name="normal" duration-ms="120" started-at="2018-10-13T16:09:13Z" data-provider="query" finished-at="2018-10-13T16:09:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[xquery version '1.0-ml'; let $a := 1 return $a]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@b3d7190]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- normal -->
        <test-method status="PASS" signature="normal(java.lang.String, [Ljava.lang.String;)[pri:0, instance:jp.imanaga.marklogic_util.QueryRunnerTest@c038203]" name="normal" duration-ms="4" started-at="2018-10-13T16:09:13Z" data-provider="query" finished-at="2018-10-13T16:09:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[xquery version '1.0-ml'; xdmp:log('aaa')]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@5fdba6f9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- normal -->
        <test-method status="PASS" signature="normal(java.lang.String, [Ljava.lang.String;)[pri:0, instance:jp.imanaga.marklogic_util.QueryRunnerTest@c038203]" name="normal" duration-ms="6" started-at="2018-10-13T16:09:13Z" data-provider="query" finished-at="2018-10-13T16:09:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[xquery version '1.0-ml'; cts:search(/, cts:word-query('aaa'))]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@10d59286]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- normal -->
        <test-method status="PASS" signature="testAbnormalConnection()[pri:0, instance:jp.imanaga.marklogic_util.QueryRunnerTest@c038203]" name="testAbnormalConnection" duration-ms="3" started-at="2018-10-13T16:09:13Z" finished-at="2018-10-13T16:09:13Z">
          <exception class="com.marklogic.xcc.exceptions.XccConfigException">
            <message>
              <![CDATA[Unrecognized connection scheme: null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.marklogic.xcc.exceptions.XccConfigException: Unrecognized connection scheme: null
at com.marklogic.xcc.ContentSourceFactory.newContentSource(ContentSourceFactory.java:146)
at com.marklogic.xcc.ContentSourceFactory.newContentSource(ContentSourceFactory.java:187)
at jp.imanaga.marklogic_util.QueryRunnerImpl.<init>(QueryRunnerImpl.java:24)
at jp.imanaga.marklogic_util.QueryRunnerTest.testAbnormalConnection(QueryRunnerTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.marklogic.xcc.exceptions.XccConfigException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAbnormalConnection -->
        <test-method status="PASS" signature="testAbnormalQuery()[pri:0, instance:jp.imanaga.marklogic_util.QueryRunnerTest@c038203]" name="testAbnormalQuery" duration-ms="11" started-at="2018-10-13T16:09:13Z" finished-at="2018-10-13T16:09:13Z">
          <exception class="com.marklogic.xcc.exceptions.XQueryException">
            <message>
              <![CDATA[Missing context item]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.marklogic.xcc.exceptions.XQueryException: XDMP-MISSINGCONTEXT: (err:XPDY0002) xxx -- Missing context item
 [Session: user=admin, cb=Documents [ContentSource: user=admin, cb=Documents [provider: address=localhost/127.0.0.1:8000, pool=1/64]]]
 [Client: XCC/8.0-8, Server: XDBC/8.0-9]
in /eval, on line 1
expr: xxx
at com.marklogic.xcc.impl.handlers.ServerExceptionHandler.handleResponse(ServerExceptionHandler.java:34)
at com.marklogic.xcc.impl.handlers.EvalRequestController.serverDialog(EvalRequestController.java:96)
at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:87)
at com.marklogic.xcc.impl.SessionImpl.submitRequestInternal(SessionImpl.java:486)
at com.marklogic.xcc.impl.SessionImpl.submitRequest(SessionImpl.java:481)
at jp.imanaga.marklogic_util.QueryRunnerImpl.exec(QueryRunnerImpl.java:33)
at jp.imanaga.marklogic_util.QueryRunnerTest.testAbnormalQuery(QueryRunnerTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.marklogic.xcc.exceptions.XQueryException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAbnormalQuery -->
      </class> <!-- jp.imanaga.marklogic_util.QueryRunnerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
